# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_xactonomial_wrappers", use_symbols = TRUE, package_name = "xactonomial")
#' @usage NULL
#' @useDynLib xactonomial, .registration = TRUE
NULL

#' Return a random sample from the d unit simplex
#' @export
sample_unit_simplex <- function(d) .Call(wrap__sample_unit_simplex, d)

#' Return n random samples from the d unit simplex
#' @export
sample_unit_simplexn <- function(d, n) .Call(wrap__sample_unit_simplexn, d, n)

#' Return a random sample from the d unit simplex
#' @export
sample_unit_simplex2 <- function(d) .Call(wrap__sample_unit_simplex2, d)

#' calculate multinomial probabilities
#' @export
calc_probs_rust <- function(sar, logt, logc, d, n, nt) .Call(wrap__calc_probs_rust, sar, logt, logc, d, n, nt)

#' sample from a gamma(k, 1)
#' @export
sample_gamma <- function(k) .Call(wrap__sample_gamma, k)

#' sample from a dirichlet(n, alpha)
#' @export
sample_dirichlet <- function(n, alpha) matrix(.Call(wrap__sample_dirichlet, n, alpha, length(alpha)), ncol = length(alpha), byrow = TRUE)


#' sample space of multinomial
#' @export
sspace_multinom <- function(d, n) matrix(.Call(wrap__sspace_multinom_rust, d, n), nrow = choose(n + d - 1, d - 1), byrow = TRUE)
